server:
  port: 8770
  
spring:  cloud:    config:      server:        git:          uri: https://github.com/chiarella/microservices  
          default-label: main               search-paths: repositorio
          
          